#!/usr/bin/env python3
"""Repair ConnectRPC v0.11.0 same-file imports for nested Google modules."""

from __future__ import annotations

import re
from pathlib import Path


GENERATED_PYTHON = Path("gen/python")
GENERATOR_VERSION = "v0.11.0"
GENERATOR_PARAMETER = "protobuf=google"
GENERATOR_HEADER = re.compile(
    r'^# Generated by protoc-gen-connectrpc-py (?P<version>\S+) with parameter "(?P<parameter>[^"]+)"\.$'
)
GOOGLE_PROTOBUF_CODEC_MARKERS = (
    "from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs",
    "_DEFAULT_CODECS = google_protobuf_codecs()",
    "_PROTO_BINARY_CODEC = google_protobuf_binary_codec()",
)
SAME_FILE_IMPORT = re.compile(
    r"^from (?P<dots>\.+)(?P<module>[A-Za-z_][A-Za-z0-9_]*_pb2) import (?P<symbols>.+)$",
    flags=re.MULTILINE,
)


def validate_generated_source(
    connect_module: Path,
    generated_python: Path,
    source: str,
) -> None:
    relative_path = connect_module.relative_to(generated_python)
    proto_name = f"{connect_module.stem.removesuffix('_connect')}.proto"
    expected_source_header = (
        f"# Generated from {relative_path.with_name(proto_name).as_posix()}. DO NOT EDIT."
    )
    lines = source.splitlines()
    if not lines or lines[0] != expected_source_header:
        raise ValueError(
            f"expected generated source header {expected_source_header!r} in "
            f"{connect_module}"
        )

    generator_header = GENERATOR_HEADER.fullmatch(lines[1]) if len(lines) > 1 else None
    if generator_header is None:
        raise ValueError(
            f"expected protoc-gen-connectrpc-py generated header in {connect_module}"
        )
    if generator_header.group("version") != GENERATOR_VERSION:
        raise ValueError(
            f"unsupported ConnectRPC generator version "
            f"{generator_header.group('version')!r} in {connect_module}; "
            f"expected {GENERATOR_VERSION!r}"
        )
    if generator_header.group("parameter") != GENERATOR_PARAMETER:
        raise ValueError(
            f"expected ConnectRPC {GENERATOR_VERSION} Google Protobuf mode in "
            f"{connect_module}, found parameter "
            f"{generator_header.group('parameter')!r}"
        )

    for marker in GOOGLE_PROTOBUF_CODEC_MARKERS:
        marker_count = lines.count(marker)
        if marker_count != 1:
            raise ValueError(
                f"expected exactly one Google Protobuf codec marker {marker!r} in "
                f"{connect_module}, found {marker_count}"
            )


def repair_generated_imports(generated_python: Path) -> int:
    connect_modules = sorted(generated_python.rglob("*_connect.py"))
    if not connect_modules:
        raise ValueError(
            f"no generated ConnectRPC modules found under {generated_python}"
        )

    repaired = 0
    for connect_module in connect_modules:
        source = connect_module.read_text(encoding="utf-8")
        validate_generated_source(connect_module, generated_python, source)

        message_module = f"{connect_module.stem.removesuffix('_connect')}_pb2"
        message_path = connect_module.with_name(f"{message_module}.py")
        if not message_path.is_file():
            raise ValueError(
                f"expected sibling message module {message_path} for {connect_module}"
            )

        candidates = [
            match
            for match in SAME_FILE_IMPORT.finditer(source)
            if match.group("module") == message_module
        ]
        if len(candidates) != 1:
            raise ValueError(
                f"expected exactly one same-file import for {message_module} in "
                f"{connect_module}, found {len(candidates)}"
            )

        candidate = candidates[0]
        if len(candidate.group("dots")) > 1:
            replacement = (
                f"from .{message_module} import {candidate.group('symbols')}"
            )
            fixed = source[: candidate.start()] + replacement + source[candidate.end() :]
            connect_module.write_text(fixed, encoding="utf-8")
            repaired += 1
        else:
            fixed = source

        if re.search(
            rf"^from \.{{2,}}{re.escape(message_module)} import ",
            fixed,
            flags=re.MULTILINE,
        ):
            raise ValueError(
                f"beyond-top-level same-file import remains in {connect_module}"
            )

    return repaired


def main() -> None:
    try:
        repaired = repair_generated_imports(GENERATED_PYTHON)
    except ValueError as error:
        raise SystemExit(str(error)) from error

    connect_module_count = sum(
        1 for _ in GENERATED_PYTHON.rglob("*_connect.py")
    )
    print(
        "ConnectRPC Python imports ready: "
        f"{connect_module_count} modules, {repaired} repaired"
    )


if __name__ == "__main__":
    main()
