import tempfile
import unittest
from pathlib import Path

from scripts.fix_connectrpc_python_imports import repair_generated_imports


class FixConnectRPCPythonImportsTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary_directory.cleanup)
        self.generated_python = Path(self.temporary_directory.name) / "gen/python"
        self.service_directory = self.generated_python / "acme/example/v1"
        self.service_directory.mkdir(parents=True)
        self.message_module = self.service_directory / "example_service_pb2.py"
        self.message_module.write_text("# generated messages\n")
        self.connect_module = self.service_directory / "example_service_connect.py"

    def generated_source(
        self,
        imports: str,
        *,
        version: str = "v0.11.0",
        protobuf: str = "google",
        include_google_codecs: bool = True,
    ) -> str:
        source = (
            "# Generated from acme/example/v1/example_service.proto. DO NOT EDIT.\n"
            f"# Generated by protoc-gen-connectrpc-py {version} with parameter "
            f"\"protobuf={protobuf}\".\n"
        )
        if include_google_codecs:
            source += (
                "from connectrpc.compat import google_protobuf_binary_codec, "
                "google_protobuf_codecs\n"
                "_DEFAULT_CODECS = google_protobuf_codecs()\n"
                "_PROTO_BINARY_CODEC = google_protobuf_binary_codec()\n"
            )
        return source + imports

    def test_repairs_only_the_derived_same_file_import(self) -> None:
        source = self.generated_source(
            "from acme.common.v1.common_pb2 import Common\n"
            "from ....example_service_pb2 import Request, Response\n"
        )
        self.connect_module.write_text(source)

        repaired = repair_generated_imports(self.generated_python)

        self.assertEqual(repaired, 1)
        self.assertEqual(
            self.connect_module.read_text(),
            source.replace(
                "from ....example_service_pb2",
                "from .example_service_pb2",
            ),
        )

    def test_rejects_an_unsupported_generator_version(self) -> None:
        self.connect_module.write_text(
            self.generated_source(
                "from ....example_service_pb2 import Request, Response\n",
                version="v0.12.0",
            )
        )

        with self.assertRaisesRegex(ValueError, "unsupported ConnectRPC generator"):
            repair_generated_imports(self.generated_python)

    def test_rejects_a_non_generated_module_without_the_source_header(self) -> None:
        self.connect_module.write_text(
            "from connectrpc.compat import google_protobuf_binary_codec, "
            "google_protobuf_codecs\n"
            "from ....example_service_pb2 import Request, Response\n"
        )

        with self.assertRaisesRegex(ValueError, "generated source header"):
            repair_generated_imports(self.generated_python)

    def test_rejects_non_google_protobuf_mode(self) -> None:
        self.connect_module.write_text(
            self.generated_source(
                "from ....example_service_pb2 import Request, Response\n",
                protobuf="py",
                include_google_codecs=False,
            )
        )

        with self.assertRaisesRegex(ValueError, "Google Protobuf mode"):
            repair_generated_imports(self.generated_python)

    def test_rejects_google_mode_without_google_codec_markers(self) -> None:
        self.connect_module.write_text(
            self.generated_source(
                "from ....example_service_pb2 import Request, Response\n",
                include_google_codecs=False,
            )
        )

        with self.assertRaisesRegex(ValueError, "Google Protobuf codec marker"):
            repair_generated_imports(self.generated_python)

    def test_rejects_an_affected_module_without_its_sibling_messages(self) -> None:
        self.message_module.unlink()
        self.connect_module.write_text(
            self.generated_source(
                "from ....example_service_pb2 import Request, Response\n"
            )
        )

        with self.assertRaisesRegex(ValueError, "sibling message module"):
            repair_generated_imports(self.generated_python)

    def test_rejects_zero_same_file_import_candidates(self) -> None:
        self.connect_module.write_text(
            self.generated_source(
                "from acme.common.v1.common_pb2 import Common\n"
            )
        )

        with self.assertRaisesRegex(ValueError, "exactly one same-file import"):
            repair_generated_imports(self.generated_python)

    def test_rejects_multiple_same_file_import_candidates(self) -> None:
        self.connect_module.write_text(
            self.generated_source(
                "from ....example_service_pb2 import Request\n"
                "from ....example_service_pb2 import Response\n"
            )
        )

        with self.assertRaisesRegex(ValueError, "exactly one same-file import"):
            repair_generated_imports(self.generated_python)


if __name__ == "__main__":
    unittest.main()
